### PR TITLE
Update from plutosdr repo

### PR DESCRIPTION
**Pull request by bkerler**
This updates the antsdr-fw from the analogio plutosdr-fw repo

### CODE REVIEW

**Comment by black-pigeon** [comment]
Hello,  are all these changes  used to keep up with upstream plutosdr firmware?

**Comment by bkerler** [comment]
Hi yes :)

**Comment by MicroPhase** [comment]
Maybe we could create a new branch named [update](https://github.com/MicroPhase/antsdr-fw/tree/update)  in our repo, and then you can commit your P&R in that branch. We will review changes in that branch.

**Comment by bkerler** [comment]
As you wish :)

**Pull request closed without merging**
