### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bkerler**
Fix needed libraries to be installed in order to make vivado run and compile the firmware (otherwise Makefile will hang)

### CODE REVIEW

**Comment by bkerler** [comment]
@Localacct21 I've updated several repos from MicroPhase, so I needed to write a pr for them first. I will reopen as soon as the other prs were accepted.

**Comment by Localacct21** [comment]
Okay. I'm about to try your new Firmware. I'll post any issues on your tree

**Comment by Localacct21** [comment]
Also libssl.1.0.dev is not available anymore I suggest you tell everyone to use libssl1.0

**Review by MicroPhase — APPROVED** [review]
libraries update, thanks for your work.

**Review by MicroPhase — APPROVED** [review]
Fix typo

**Comment by Localacct21** [comment]
Good  Job @bkerler  and thanks for the quick merge @MicroPhase

**Comment by MicroPhase** [comment]
The submodule needs to be verified first, so close this PR now, thanks for your PR.

**Pull request closed without merging**
